name = "MINLPTests"
uuid = "ee0a3090-8ee9-5cdb-b8cb-8eeba3165522"
repo = "https://github.com/JuliaOpt/MINLPTests.jl.git"
version = "0.2.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
Ipopt = "≥ 0.5.0"
JuMP = "~0.18"
Juniper = "≥ 0.2.2"
julia = "^1"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Juniper", "Ipopt"]
